// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
	Provider *string `json:"provider,omitempty"`
	Avi      *string `json:"avi,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Username *string `json:"username,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Provider *string `json:"provider,omitempty"`
	Email    *string `json:"email,omitempty"`
	Avi      *string `json:"avi,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Username *string `json:"username,omitempty"`
	Jwt      *string `json:"jwt,omitempty"`
}
