// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	Token    string  `json:"token"`
	Email    string  `json:"email"`
	Name     string  `json:"name"`
	Provider string  `json:"provider"`
	Avi      *string `json:"avi,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Username *string `json:"username,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Provider *string `json:"provider,omitempty"`
	Email    *string `json:"email,omitempty"`
	Avi      *string `json:"avi,omitempty"`
	Sex      *string `json:"sex,omitempty"`
	Username *string `json:"username,omitempty"`
	Jwt      *string `json:"jwt,omitempty"`
}
